all:
	gcc -w scheduler.c -o scheduler
	gcc -w process.c -o process
	gcc -w FIFO.c -o FIFO
	gcc -w RR.c -o RR
	gcc -w SJF.c heap.c -o SJF
	gcc -w PSJF.c heap.c -o PSJF
clean:
	rm scheduler process FIFO RR SJF PSJF
